import pg from 'pg';

export interface ReviewItem {
  id: string;
  type: 'gap' | 'flagged_faq' | 'suggestion' | 'stale';
  title: string;
  description: string;
  priority: 'high' | 'medium' | 'low';
  data: Record<string, unknown>;
  createdAt: Date;
}

/**
 * Gets all pending review items across gaps, flagged FAQs, and suggestions.
 */
export async function getReviewQueue(pool: pg.Pool): Promise<ReviewItem[]> {
  const items: ReviewItem[] = [];

  // Pending knowledge gaps
  const gaps = await pool.query(
    `SELECT id, representative_question, sample_queries, cluster_size, priority, created_at
     FROM faq_gaps WHERE status = 'pending' ORDER BY
       CASE priority WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,
       cluster_size DESC`
  );

  for (const g of gaps.rows) {
    items.push({
      id: g.id,
      type: 'gap',
      title: g.representative_question,
      description: `${g.cluster_size} users asked this — no FAQ exists`,
      priority: g.priority,
      data: { sampleQueries: g.sample_queries, clusterSize: g.cluster_size },
      createdAt: g.created_at,
    });
  }

  // Pending improvement suggestions
  const suggestions = await pool.query(
    `SELECT s.id, s.suggestion_type, s.suggestion_text, s.evidence, s.created_at,
            faq.question
     FROM improvement_suggestions s
     JOIN faq_entries faq ON faq.id = s.faq_entry_id
     WHERE s.status = 'pending'
     ORDER BY s.created_at DESC`
  );

  for (const s of suggestions.rows) {
    items.push({
      id: s.id,
      type: 'suggestion',
      title: `${s.suggestion_type}: "${s.question}"`,
      description: s.suggestion_text,
      priority: 'medium',
      data: { suggestionType: s.suggestion_type, evidence: s.evidence, faqQuestion: s.question },
      createdAt: s.created_at,
    });
  }

  return items;
}

/**
 * Approve a knowledge gap — creates a new FAQ entry from it.
 */
export async function approveGap(
  pool: pg.Pool,
  gapId: string,
  faqData: { question: string; answer: string; category?: string }
): Promise<string> {
  // Mark gap as approved
  await pool.query(
    `UPDATE faq_gaps SET status = 'approved', reviewed_at = now() WHERE id = $1`,
    [gapId]
  );

  // Insert new FAQ entry (embeddings will be generated by the bot's upsertFAQ)
  const result = await pool.query(
    `INSERT INTO faq_entries (question, answer, category, metadata)
     VALUES ($1, $2, $3, $4) RETURNING id`,
    [faqData.question, faqData.answer, faqData.category || null, JSON.stringify({ source: 'gap-approved', gapId })]
  );

  const faqId = result.rows[0].id;

  // Link gap to the new FAQ
  await pool.query(
    `UPDATE faq_gaps SET resolved_faq_id = $1 WHERE id = $2`,
    [faqId, gapId]
  );

  return faqId;
}

/**
 * Dismiss a knowledge gap.
 */
export async function dismissGap(pool: pg.Pool, gapId: string): Promise<void> {
  await pool.query(
    `UPDATE faq_gaps SET status = 'dismissed', reviewed_at = now() WHERE id = $1`,
    [gapId]
  );
}

/**
 * Approve an improvement suggestion.
 */
export async function approveSuggestion(pool: pg.Pool, suggestionId: string): Promise<void> {
  await pool.query(
    `UPDATE improvement_suggestions SET status = 'approved', reviewed_at = now() WHERE id = $1`,
    [suggestionId]
  );
}

/**
 * Dismiss an improvement suggestion.
 */
export async function dismissSuggestion(pool: pg.Pool, suggestionId: string): Promise<void> {
  await pool.query(
    `UPDATE improvement_suggestions SET status = 'dismissed', reviewed_at = now() WHERE id = $1`,
    [suggestionId]
  );
}

/**
 * Save detected gaps to the database.
 */
export async function saveGaps(
  pool: pg.Pool,
  gaps: Array<{ representativeQuestion: string; sampleQueries: string[]; clusterSize: number; priority: string }>
): Promise<number> {
  let saved = 0;
  for (const gap of gaps) {
    // Check if similar gap already exists (avoid duplicates)
    const existing = await pool.query(
      `SELECT id FROM faq_gaps
       WHERE representative_question = $1 AND status = 'pending'`,
      [gap.representativeQuestion]
    );

    if (existing.rows.length === 0) {
      await pool.query(
        `INSERT INTO faq_gaps (representative_question, sample_queries, cluster_size, priority)
         VALUES ($1, $2, $3, $4)`,
        [gap.representativeQuestion, gap.sampleQueries, gap.clusterSize, gap.priority]
      );
      saved++;
    }
  }
  return saved;
}
